version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt -t .

  build:
    commands:
      - echo "Running unit tests..."
      - pytest tests/
      - echo "Packaging application..."
      - zip -r my-app.zip .

  post_build:
    commands:
      - echo "Uploading to S3..."
      - aws s3 cp my-app.zip s3://my-s3-bucket/my-app.zip
      - echo "Triggering Lambda for deployment..."
      - aws lambda invoke --function-name trigger-codedeploy-deployment output.json
artifacts:
  files:
    - my-app.zip
